### ISSUE TITLE
项目启动错误

### ISSUE THREAD

**Issue by dxl3811051** [binwen/django-db-pool#3]
你好 我完全按照你的配置配置好后 启动项目 报错  'djdbpool.db.backends.mysql' isn't an available database backend

**Comment by dxl3811051** [comment]
我的python3.8 django3.1

**Comment by caowenbin** [comment]
在py3.8与dj3情况下 
DBUtils==2.0
six==1.15.0
由DBUtils2.0版本api变动、django去掉six依赖引起
建议安装django-database-pool==0.0.3
